POST http://localhost:8000/api/auth/login
Content-Type: application/json

{
  "email": "nahom.@gmail.com",
  "password": "password"

}


# POST http://localhost:8000/api/auth/signup
# Content-Type: application/json

# {
#   "username":"nahomjs",
#   "email": "nahom.@gmail.com",
#   "password": "password"

# }
