# POST  http://localhost:8000/api/auth/login
# Content-Type: application/json

# {
#   "email": "nnnnnahom.@gmail.com",
#   "password": "password"

# }

GET    http://localhost:8000/api/listing/get?type=sale

# GET      http://localhost:8000/api/user/getListing/6699ab37d62a7bc056507216
# Content-Type: application/json

# {
#   "name": "test_comp",
#     "description": "test1",
#     "address": "test1",
#     "regularPrice": 232,
#     "discountedPrice": 123,
#     "bathrooms": 1,
#     "bedrooms": 1,
#     "furnished": false,
#     "parking": false,
#     "offer": false,
#     "imageURLs": ["a,ajakalkalakal","akjakajakjakajm"],
#     "type": "test1",
#     "userRef":"6699ab37d62a7bc056507216"

# }

























# POST http://localhost:8000/api/auth/signup
# Content-Type: application/json

# {
#   "username":"nahomjs",
#   "email": "nahom.@gmail.com",
#   "password": "password"

# }



  // const getuser=async ()=>{
  //   try {
  //     const res = await fetch('/api/user/getuser', {
  //       method: 'POST',
  //       headers: {
  //         'Content-Type': 'application/json',
  //       },
  //       body: JSON.stringify(data),
  //     });
  //     if (!res.ok) {
  //       const { error } = await res.json();
  //       dispatch(signInFailure(error.message));
  //       return;
  //     }

  //     const myuser = await res.json();
  //     console.log(myuser);
  //   } catch (error) {
  //     console.log(error);
  //   }
  // }

  // getuser()